# Generated by Django 5.2.14 on 2026-05-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'date')},
        ),
    ]
